### ISSUE TITLE
Refined Storage different folder structure

### ISSUE THREAD

**Issue by tango99** [F32Organization/Faithful32-1.12.2#100]
It seems like with the latest version of Refined Storage, the way the textures are stored is different to the layout used in this pack, which is causing the majority of them not to load.

You can see [here](https://github.com/raoulvdberge/refinedstorage/tree/mc1.12/src/main/resources/assets/refinedstorage/textures/blocks) in the Refined Storage repository that they are now using a folder structure to seperate the textures, however in the faithful version, found [here](https://github.com/F32Organization/Faithful32-1.12.2/tree/master/assets/refinedstorage/textures/blocks), the majority of the textures are still in the main directory.

I'm not sure if this is a quick fix or not but thought I would point that out. :)

**Comment by StefanTT** [comment]
Ok, thanks!

**Comment by Ethryan** [comment]
Damn, not another one.
Will fix this on saturday.

**Comment by StefanTT** [comment]
I did not have a look, but is this fixed now?

**Comment by FinalDeath61** [comment]
I don't know but i have some texture missing (transparent) Crafting monitor, controller and some other

**Comment by anders0nmat** [comment]
No significant folder structure changes left. Still missing textures though
